image: node:latest
stages:
  - deploy

deploy:
  tags:
    - smart-contract
  stage: deploy
  environment: develop
  only:
    - feature/deploy
  script:
    - echo "//registry.npmjs.org/:_auth=${NPM_TOKEN}" > .npmrc
    - echo always-auth = true >> .npmrc
    - echo email = ${EMAIL} >> .npmrc
    - npm whoami
    - npm publish --access public