image: node:latest
stages:
  - deploy

deploy:
  tag:
    - smart-contract
  stage: deploy
  only:
    - feature/deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - npm publish
