/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC20Contract } from "./ERC20";
import { IERC20Contract } from "./IERC20";
import { IERC20UniswapContract } from "./IERC20Uniswap";
import { IMigratorContract } from "./IMigrator";
import { IMigratorToSoneSwapContract } from "./IMigratorToSoneSwap";
import { ISoneConvertContract } from "./ISoneConvert";
import { ISoneSwapRouterContract } from "./ISoneSwapRouter";
import { ISoneTokenContract } from "./ISoneToken";
import { IUniswapV2CalleeContract } from "./IUniswapV2Callee";
import { IUniswapV2ERC20Contract } from "./IUniswapV2ERC20";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { IWETHContract } from "./IWETH";
import { MigrationsContract } from "./Migrations";
import { MigratorContract } from "./Migrator";
import { MockERC20Contract } from "./MockERC20";
import { OwnableContract } from "./Ownable";
import { SoneConvertContract } from "./SoneConvert";
import { SoneMasterFarmerContract } from "./SoneMasterFarmer";
import { SoneSwapRouterContract } from "./SoneSwapRouter";
import { SoneTokenContract } from "./SoneToken";
import { TimelockContract } from "./Timelock";
import { UniswapV2ERC20Contract } from "./UniswapV2ERC20";
import { UniswapV2FactoryContract } from "./UniswapV2Factory";
import { UniswapV2PairContract } from "./UniswapV2Pair";
import { UniswapV2Router02Contract } from "./UniswapV2Router02";
import { WETH9Contract } from "./WETH9";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Uniswap"): IERC20UniswapContract;
      require(name: "IMigrator"): IMigratorContract;
      require(name: "IMigratorToSoneSwap"): IMigratorToSoneSwapContract;
      require(name: "ISoneConvert"): ISoneConvertContract;
      require(name: "ISoneSwapRouter"): ISoneSwapRouterContract;
      require(name: "ISoneToken"): ISoneTokenContract;
      require(name: "IUniswapV2Callee"): IUniswapV2CalleeContract;
      require(name: "IUniswapV2ERC20"): IUniswapV2ERC20Contract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "IWETH"): IWETHContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Migrator"): MigratorContract;
      require(name: "MockERC20"): MockERC20Contract;
      require(name: "Ownable"): OwnableContract;
      require(name: "SoneConvert"): SoneConvertContract;
      require(name: "SoneMasterFarmer"): SoneMasterFarmerContract;
      require(name: "SoneSwapRouter"): SoneSwapRouterContract;
      require(name: "SoneToken"): SoneTokenContract;
      require(name: "Timelock"): TimelockContract;
      require(name: "UniswapV2ERC20"): UniswapV2ERC20Contract;
      require(name: "UniswapV2Factory"): UniswapV2FactoryContract;
      require(name: "UniswapV2Pair"): UniswapV2PairContract;
      require(name: "UniswapV2Router02"): UniswapV2Router02Contract;
      require(name: "WETH9"): WETH9Contract;
    }
  }
}

export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IERC20UniswapContract, IERC20UniswapInstance } from "./IERC20Uniswap";
export { IMigratorContract, IMigratorInstance } from "./IMigrator";
export {
  IMigratorToSoneSwapContract,
  IMigratorToSoneSwapInstance,
} from "./IMigratorToSoneSwap";
export { ISoneConvertContract, ISoneConvertInstance } from "./ISoneConvert";
export {
  ISoneSwapRouterContract,
  ISoneSwapRouterInstance,
} from "./ISoneSwapRouter";
export { ISoneTokenContract, ISoneTokenInstance } from "./ISoneToken";
export {
  IUniswapV2CalleeContract,
  IUniswapV2CalleeInstance,
} from "./IUniswapV2Callee";
export {
  IUniswapV2ERC20Contract,
  IUniswapV2ERC20Instance,
} from "./IUniswapV2ERC20";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance,
} from "./IUniswapV2Factory";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance,
} from "./IUniswapV2Pair";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance,
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance,
} from "./IUniswapV2Router02";
export { IWETHContract, IWETHInstance } from "./IWETH";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { MigratorContract, MigratorInstance } from "./Migrator";
export { MockERC20Contract, MockERC20Instance } from "./MockERC20";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { SoneConvertContract, SoneConvertInstance } from "./SoneConvert";
export {
  SoneMasterFarmerContract,
  SoneMasterFarmerInstance,
} from "./SoneMasterFarmer";
export {
  SoneSwapRouterContract,
  SoneSwapRouterInstance,
} from "./SoneSwapRouter";
export { SoneTokenContract, SoneTokenInstance } from "./SoneToken";
export { TimelockContract, TimelockInstance } from "./Timelock";
export {
  UniswapV2ERC20Contract,
  UniswapV2ERC20Instance,
} from "./UniswapV2ERC20";
export {
  UniswapV2FactoryContract,
  UniswapV2FactoryInstance,
} from "./UniswapV2Factory";
export { UniswapV2PairContract, UniswapV2PairInstance } from "./UniswapV2Pair";
export {
  UniswapV2Router02Contract,
  UniswapV2Router02Instance,
} from "./UniswapV2Router02";
export { WETH9Contract, WETH9Instance } from "./WETH9";
