/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ISoneConvertContract
  extends Truffle.Contract<ISoneConvertInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<ISoneConvertInstance>;
}

type AllEvents = never;

export interface ISoneConvertInstance extends Truffle.ContractInstance {
  convertToSone: {
    (
      token0: string,
      token1: string,
      liquidity: number | BN | string,
      totalSupply: number | BN | string,
      to: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      token0: string,
      token1: string,
      liquidity: number | BN | string,
      totalSupply: number | BN | string,
      to: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      token0: string,
      token1: string,
      liquidity: number | BN | string,
      totalSupply: number | BN | string,
      to: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      token0: string,
      token1: string,
      liquidity: number | BN | string,
      totalSupply: number | BN | string,
      to: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    convertToSone: {
      (
        token0: string,
        token1: string,
        liquidity: number | BN | string,
        totalSupply: number | BN | string,
        to: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        token0: string,
        token1: string,
        liquidity: number | BN | string,
        totalSupply: number | BN | string,
        to: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        token0: string,
        token1: string,
        liquidity: number | BN | string,
        totalSupply: number | BN | string,
        to: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        token0: string,
        token1: string,
        liquidity: number | BN | string,
        totalSupply: number | BN | string,
        to: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
