/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface MigratorContract extends Truffle.Contract<MigratorInstance> {
  "new"(
    _soneMaster: string,
    _oldFactory: string,
    _factory: string,
    _notBeforeBlock: number | BN | string,
    meta?: Truffle.TransactionDetails
  ): Promise<MigratorInstance>;
}

type AllEvents = never;

export interface MigratorInstance extends Truffle.ContractInstance {
  desiredLiquidity(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  factory(txDetails?: Truffle.TransactionDetails): Promise<string>;

  notBeforeBlock(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  oldFactory(txDetails?: Truffle.TransactionDetails): Promise<string>;

  soneMaster(txDetails?: Truffle.TransactionDetails): Promise<string>;

  migrate: {
    (orig: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(orig: string, txDetails?: Truffle.TransactionDetails): Promise<string>;
    sendTransaction(
      orig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      orig: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    desiredLiquidity(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    factory(txDetails?: Truffle.TransactionDetails): Promise<string>;

    notBeforeBlock(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    oldFactory(txDetails?: Truffle.TransactionDetails): Promise<string>;

    soneMaster(txDetails?: Truffle.TransactionDetails): Promise<string>;

    migrate: {
      (orig: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        orig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        orig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        orig: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
